baseURL = 'https://aym-js.emaxilde.net/'
languageCode = 'en'
title = 'AYM·JS'

[params]
title       = 'AYM·JS'
tagline     = 'A sound chip emulator written in JavaScript and Web Audio'
charset     = 'utf-8'
viewport    = 'width=device-width, initial-scale=1.0'
description = 'AYM·JS is a sound chip emulator written in JavaScript and designed to emulate the AY-3-8910 PSG (Programmable Sound Generator) and the YM2149 SSG (Software-Controlled Sound Generator).'
keywords    = 'AY-3-8910, AY-3-8912, AY-3-8913, YM2149, Programmable Sound Generator, Software-Controlled Sound Generator, Emulator, JavaScript'
author      = 'Olivier Poncet'
copyright   = 'Copyright © 2001-2023'
images      = ['assets/images/aym-js-banner.jpg']

[params.links]
twitter   = 'https://twitter.com/ponceto91'
bluesky   = 'https://bsky.app/profile/ponceto91.bsky.social'
linkedin  = 'https://www.linkedin.com/in/olivier-poncet-33369010/'
twitch    = 'https://twitch.tv/ponceto91'
youtube   = 'https://youtube.com/ponceto91'
github    = 'https://github.com/ponceto/aym-js'
gitlab    = 'https://gitlab.com/ponceto/aym-js'
bitbucket = 'https://bitbucket.org/ponceto/aym-js'

[params.icons]
twitter   = 'fa-brands fa-square-x-twitter'
bluesky   = 'fa-solid fa-square'
linkedin  = 'fa-brands fa-linkedin'
twitch    = 'fa-brands fa-twitch'
youtube   = 'fa-brands fa-youtube'
github    = 'fa-brands fa-square-github'
gitlab    = 'fa-brands fa-square-gitlab'
bitbucket = 'fa-brands fa-bitbucket'
play      = 'fa-solid fa-play'
stop      = 'fa-solid fa-stop'
prev      = 'fa-solid fa-backward-step'
next      = 'fa-solid fa-forward-step'
power     = 'fa-solid fa-power-off'
reset     = 'fa-solid fa-rotate'
pause     = 'fa-solid fa-pause'
mutea     = 'fa-solid fa-volume-xmark'
muteb     = 'fa-solid fa-volume-xmark'
mutec     = 'fa-solid fa-volume-xmark'

[params.labels]
twitter   = 'Follow me on Twitter'
bluesky   = 'Follow me on Bluesky'
linkedin  = 'Follow me on LinkedIn'
twitch    = 'Follow me on Twitch'
youtube   = 'Follow me on YouTube'
github    = 'Follow me on GitHub'
gitlab    = 'Follow me on GitLab'
bitbucket = 'Follow me on Bitbucket'
play      = 'Play'
stop      = 'Stop'
next      = 'Next'
prev      = 'Prev'
power     = 'Power'
reset     = 'Reset'
pause     = 'Pause'
mutea     = 'Mute A'
muteb     = 'Mute B'
mutec     = 'Mute C'
